(()=>{
  const $=s=>document.querySelector(s);
  const baseCases=[
    {title:'The Missing 10 Minutes',setup:'7:10 PM · Living room. Ava becomes verbally escalated toward a housemate after they enter the shared space.',timeline:[['7:10 PM','Ava raises her voice toward a housemate in the living room.'],['7:11 PM','Ava states, “Get away from me. I don’t want you near me.”'],['7:12 PM','Staff uses a calm tone and supports separation without arguing about what happened.'],['7:15 PM','Ava moves to the hallway and continues pacing.'],['7:19 PM','Ava stops yelling and asks for space.'],['7:22 PM','Ava returns to the living room after the other person has moved to another area.']],items:[['At 7:10 PM, Ava raised her voice toward a housemate in the living room.','observed','note'],['“Get away from me. I don’t want you near me.”','quote','note'],['Staff maintained a calm tone and supported separation of the two individuals.','staff','note'],['Ava moved to the hallway, paced for several minutes, and then asked for space.','response','note'],['By 7:22 PM, Ava had stopped yelling and returned to the living room without further escalation.','outcome','note'],['The television was on during the interaction.','observed','omit'],['Ava had been sitting on the couch before the housemate entered.','observed','omit'],['Ava was being disrespectful.','bad','trash'],['Ava wanted to start drama with the housemate.','bad','trash'],['Staff handled the situation appropriately.','bad','trash']]},
    {title:'What Did Staff Actually Do?',setup:'9:15 PM · Hallway. Jalen shoves staff with open hands while saying, “Get out of my way.” The draft note later says only, “Staff redirected Jalen.”',timeline:[['9:15 PM','Jalen shoves staff with open hands in the hallway.'],['9:15 PM','Jalen states, “Get out of my way.”'],['9:16 PM','Staff disengages immediately and increases distance without physical response.'],['9:18 PM','Jalen walks to his room and closes the door.'],['9:26 PM','Staff checks in from the doorway after Jalen’s voice and pacing have decreased.'],['9:30 PM','Jalen speaks with staff about what could help earlier next time.']],items:[['At 9:15 PM, Jalen shoved staff with open hands in the hallway.','observed','note'],['“Get out of my way.”','quote','note'],['Staff disengaged immediately and increased distance without physical response.','staff','note'],['Jalen walked to his room, closed the door, and remained there for several minutes.','response','note'],['At approximately 9:30 PM, Jalen re-engaged in conversation with staff about earlier coping options.','outcome','note'],['Staff had been completing shift paperwork before the incident.','observed','omit'],['The hallway light was on.','observed','omit'],['Jalen attacked staff.','bad','trash'],['Jalen was out of control.','bad','trash'],['Staff successfully de-escalated Jalen.','bad','trash']]},
    {title:'The Fall Note',setup:'7:40 PM · Hallway. Sienna slips and falls to the floor while walking toward the kitchen.',timeline:[['7:40 PM','Sienna slips in the hallway and falls to the floor.'],['7:41 PM','Sienna states, “I’m okay. I just lost my balance.”'],['7:42 PM','Staff visually checks for injury and asks about pain.'],['7:44 PM','Sienna denies pain and no injury is observed.'],['7:47 PM','Sienna stands and walks to the kitchen without assistance.'],['8:00 PM','Sienna continues normal activity with no new complaint.']],items:[['At 7:40 PM, Sienna slipped in the hallway and fell to the floor.','observed','note'],['“I’m okay. I just lost my balance.”','quote','note'],['Staff visually assessed for injury and asked Sienna about pain.','staff','note'],['Sienna denied pain, and no injury was reported or observed.','response','note'],['Sienna stood, walked to the kitchen without assistance, and had no new complaint by 8:00 PM.','outcome','note'],['Sienna had socks on at the time.','observed','omit'],['Dinner was being prepared in the kitchen.','observed','omit'],['Sienna was clumsy.','bad','trash'],['Sienna fell because she was not paying attention.','bad','trash'],['No big deal.','bad','trash']]},
    {title:'Property Damage',setup:'4:19 PM · Bedroom. Rowan throws their glasses onto the floor during emotional escalation, and the glasses break.',timeline:[['4:19 PM','Rowan raises their voice while pacing in the bedroom.'],['4:19 PM','Rowan throws their glasses onto the floor and states, “I don’t care anymore.”'],['4:20 PM','Staff provides space and does not continue the argument.'],['4:28 PM','Rowan’s voice lowers and pacing slows.'],['4:31 PM','Staff re-engages with Rowan about what happened.'],['4:35 PM','Rowan states, “Next time I’ll put them down instead.”']],items:[['At 4:19 PM, Rowan threw their glasses onto the bedroom floor, causing them to break.','observed','note'],['“I don’t care anymore.”','quote','note'],['Staff provided space and re-engaged once Rowan’s escalation had decreased.','staff','note'],['Rowan’s voice lowered, pacing slowed, and they later spoke with staff about the incident.','response','note'],['Rowan stated, “Next time I’ll put them down instead,” identifying a possible prevention strategy.','outcome','note'],['Rowan had worn the glasses all day.','observed','omit'],['A laundry basket was beside the bed.','observed','omit'],['Rowan does not respect their belongings.','bad','trash'],['Rowan broke the glasses for attention.','bad','trash'],['Rowan learned their lesson.','bad','trash']]},
    {title:'Whose Item Is It?',setup:'6:10 PM · Living room. Malik takes a personal item belonging to a housemate and brings it to his bedroom.',timeline:[['6:10 PM','Malik picks up a housemate’s personal item from the living room.'],['6:11 PM','Malik brings the item to his bedroom.'],['6:13 PM','Staff checks in and asks Malik about the item.'],['6:14 PM','Malik states, “I just wanted it for a bit.”'],['6:16 PM','Staff discusses personal boundaries and asks what Malik wants to do next.'],['6:18 PM','Malik returns the item to the housemate without further issue.']],items:[['At approximately 6:10 PM, Malik took a personal item belonging to a housemate from the living room and brought it to his bedroom.','observed','note'],['“I just wanted it for a bit.”','quote','note'],['Staff remained calm and discussed personal belongings and boundaries.','staff','note'],['Malik returned the item after speaking with staff.','response','note'],['By 6:18 PM, the item had been returned and no further conflict occurred.','outcome','note'],['The item had been left on a chair.','observed','omit'],['Malik had been in the living room earlier that afternoon.','observed','omit'],['Malik stole the item.','bad','trash'],['Malik knew better.','bad','trash'],['Malik was trying to upset the housemate.','bad','trash']]},
    {title:'The Medical Detail That Matters',setup:'4:50 PM · Living room. Priya experiences a brief seizure while seated.',timeline:[['4:50 PM','Priya has a seizure while seated in the living room.'],['4:50 PM','The episode lasts approximately 30 seconds.'],['4:51 PM','Staff clears the immediate area and monitors without physical intervention.'],['4:53 PM','Priya is responsive and states, “I’m okay, just tired.”'],['4:58 PM','Priya remains seated and continues responding to staff.'],['5:00 PM','Required notification is completed according to the setting’s process.']],items:[['At approximately 4:50 PM, Priya experienced a seizure lasting about 30 seconds while seated in the living room.','observed','note'],['“I’m okay, just tired.”','quote','note'],['Staff ensured the surrounding area was safe and monitored Priya.','staff','note'],['Priya was responsive after the episode and reported feeling tired.','response','note'],['Required notification was completed, and Priya continued responding to staff afterward.','outcome','note'],['Priya had been watching television beforehand.','observed','omit'],['A blanket was on the couch.','observed','omit'],['Priya had a bad seizure.','bad','trash'],['Priya was fine after.','bad','trash'],['Staff did everything correctly.','bad','trash']]},
    {title:'The Safety Note',setup:'10:30 PM · Living room. Tessa scratches her forearm while distressed and states, “I just want it to stop.”',timeline:[['10:30 PM','Tessa scratches her forearm while sitting in the living room.'],['10:30 PM','Tessa states, “I just want it to stop.”'],['10:31 PM','Staff remains present and follows Tessa’s individualized safety process.'],['10:34 PM','Staff completes the required safety questions.'],['10:36 PM','Tessa states, “No, I’m not trying to kill myself.”'],['10:45 PM','Tessa accepts support and identifies coping options she wants to try.']],items:[['At approximately 10:30 PM, Tessa scratched her forearm while expressing emotional distress.','observed','note'],['“I just want it to stop.”','quote','note'],['Staff remained present, followed Tessa’s individualized safety process, and completed the required safety questions.','staff','note'],['Tessa answered the safety questions and stated, “No, I’m not trying to kill myself.”','response','note'],['Tessa accepted support and identified coping options she wanted to use; required notification was completed.','outcome','note'],['Tessa had been in the living room for most of the evening.','observed','omit'],['Tessa was wearing a sweatshirt.','observed','omit'],['Tessa was attention-seeking.','bad','trash'],['Tessa was suicidal.','bad','trash'],['Tessa was safe because she calmed down.','bad','trash']]},
    {title:'Overnight Gaps',setup:'6:50 AM · Shift change. Incoming staff reads only: “Noah was up a lot overnight.”',timeline:[['1:40 AM','Noah wakes and paces for about five minutes.'],['1:44 AM','Staff completes a brief check-in and keeps the environment low-stimulation.'],['1:47 AM','Noah declines additional support and returns to bed.'],['4:15 AM','Noah wakes and paces again for about five minutes.'],['4:22 AM','Noah returns to bed independently.'],['6:50 AM','Noah is asleep at shift change; the waking pattern was more frequent than usual.']],items:[['Noah woke at 1:40 AM and 4:15 AM and paced for about five minutes each time.','observed','note'],['“My mind won’t shut off, but I’m okay.”','quote','note'],['Staff completed brief check-ins and reduced stimulation per Noah’s usual overnight plan.','staff','note'],['Noah declined additional support both times and returned to bed independently.','response','note'],['Noah was asleep at shift change; incoming staff was told the waking pattern was more frequent than usual.','outcome','note'],['Noah used the bathroom at 3:05 AM.','observed','omit'],['The hallway light was on.','observed','omit'],['Noah was weird all night.','bad','trash'],['Noah kept staff awake unnecessarily.','bad','trash'],['Nothing important happened because Noah went back to bed.','bad','trash']]}
  ];

  const labels={observed:'WHAT HAPPENED',quote:'PERSON’S WORDS',staff:'STAFF ACTION',response:'PERSON’S RESPONSE',outcome:'FOLLOW-THROUGH'};
  const slotIds={observed:'slotObserved',quote:'slotQuote',staff:'slotStaff',response:'slotResponse',outcome:'slotOutcome'};
  const prompts={observed:'Add an observable detail here.',quote:'Use an exact quote when it matters.',staff:'What did staff actually do?',response:'What happened after staff responded?',outcome:'What changed, continued, or needs handed off?'};
  const lenses=['missing timestamps','vague staff action','judgment vs. behavior','missing person response','note ends too soon','too much irrelevant detail','safety wording'];
  const names=['Cam','Elise','Dorian','Maya','Nico','Rae','Emmett','Lena','Micah','Zoey','Andre','Mina','Cole','Jessa','Tariq','June'];
  let current=0,generated=null,sceneIndex=0,placements={},activeLens=null,lastGenerated='';
  const pick=a=>a[Math.floor(Math.random()*a.length)];
  const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
  const escape=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const caseNow=()=>generated||baseCases[current];

  function timeSet(){
    const starts=[[8,12],[10,35],[13,18],[15,42],[17,7],[18,26],[20,14],[21,33]];const [h,m]=pick(starts);
    const fmt=(hh,mm)=>{const ap=hh>=12?'PM':'AM';let hr=hh%12||12;return `${hr}:${String(mm).padStart(2,'0')} ${ap}`};
    return [0,2,4,8,13,18].map(d=>fmt(h, m+d));
  }

  function buildGeneratedCase(){
    const name=pick(names),t=timeSet(),variant=Math.floor(Math.random()*6),key=`${name}-${t[0]}-${variant}`;
    if(key===lastGenerated)return buildGeneratedCase();lastGenerated=key;
    const templates=[
      ()=>({title:'After the Busy Outing',setup:`${t[0]} · Entryway. ${name} returns home from a crowded community outing and immediately asks for less noise.`,timeline:[[t[0],`${name} enters the home, covers their ears, and says, “It was too much. I need quiet.”`],[t[1],`Staff lowers nearby noise and asks whether ${name} wants company or space.`],[t[2],`${name} chooses space and goes to the porch.`],[t[3],`${name} remains on the porch and drinks water.`],[t[4],`${name} returns inside and states, “I’m better now.”`],[t[5],`${name} chooses to sit in the living room and resumes their evening.`]],items:[[`At ${t[0]}, ${name} returned from a crowded community outing, covered their ears, and asked for quiet.`,'observed','note'],['“It was too much. I need quiet.”','quote','note'],[`Staff lowered nearby noise and offered ${name} a choice of company or space.`,'staff','note'],[`${name} chose space and went to the porch.`,'response','note'],[`${name} later returned inside, stated, “I’m better now,” and resumed their evening.`,'outcome','note'],['A grocery bag was on the counter.','observed','omit'],['The porch light was on.','observed','omit'],[`${name} was being dramatic.`,'bad','trash'],[`${name} wanted everyone to leave them alone on purpose.`,'bad','trash'],['Staff handled it perfectly.','bad','trash']]}),
      ()=>({title:'The Calendar Change',setup:`${t[0]} · Kitchen. ${name} notices an appointment time on the household calendar has changed.`,timeline:[[t[0],`${name} points to the calendar and asks, “Why did this change?”`],[t[1],`${name} asks the same question again and begins pacing between the kitchen and hallway.`],[t[2],`Staff checks the calendar information with ${name} and says what is known without guessing.`],[t[3],`${name} asks to write the new time on a sticky note.`],[t[4],`${name} places the note near their bedroom door.`],[t[5],`${name} stops pacing and begins preparing a snack.`]],items:[[`At ${t[0]}, ${name} noticed an appointment-time change and began repeatedly asking about it while pacing.`,'observed','note'],['“Why did this change?”','quote','note'],[`Staff reviewed the available calendar information with ${name} and avoided guessing about the reason for the change.`,'staff','note'],[`${name} asked to write the new time on a sticky note and placed it near their bedroom door.`,'response','note'],[`${name} stopped pacing and began preparing a snack.`,'outcome','note'],['There were magnets on the refrigerator.','observed','omit'],['A staff water bottle was on the table.','observed','omit'],[`${name} was obsessing over the appointment.`,'bad','trash'],[`${name} did not understand the calendar.`,'bad','trash'],['Staff redirected successfully.','bad','trash']]}),
      ()=>({title:'Where Are My Headphones?',setup:`${t[0]} · Bedroom doorway. ${name} cannot find their headphones and believes a housemate moved them.`,timeline:[[t[0],`${name} checks the bedroom and says, “Someone took my headphones.”`],[t[1],`${name} raises their voice and checks the living room.`],[t[2],`Staff asks what ${name} remembers about the last place they used the headphones and offers to look with them.`],[t[3],`${name} checks under the couch cushions.`],[t[4],`${name} finds the headphones under the couch and says, “Okay, I forgot I put them here.”`],[t[5],`${name} returns to their bedroom with the headphones.`]],items:[[`At ${t[0]}, ${name} reported missing headphones, raised their voice, and searched the bedroom and living room.`,'observed','note'],['“Someone took my headphones.”','quote','note'],[`Staff asked where ${name} last remembered using the headphones and offered to help look.`,'staff','note'],[`${name} searched under the couch cushions and located the headphones.`,'response','note'],[`${name} stated, “Okay, I forgot I put them here,” and returned to their bedroom with the headphones.`,'outcome','note'],['A blanket was folded on the couch.','observed','omit'],['The television remote was on the coffee table.','observed','omit'],[`${name} falsely accused a housemate of stealing.`,'bad','trash'],[`${name} was paranoid.`,'bad','trash'],['Staff proved the housemate did nothing wrong.','bad','trash']]}),
      ()=>({title:'The Plan Changed',setup:`${t[0]} · Front porch. A planned community activity is canceled because of weather, and ${name} reacts to the change.`,timeline:[[t[0],`${name} is told the outdoor activity is canceled and says, “That’s not fair. I was ready.”`],[t[1],`${name} walks onto the porch and shuts the screen door firmly.`],[t[2],`Staff acknowledges the disappointment and gives ${name} time without repeatedly offering alternatives.`],[t[3],`${name} sits on the porch steps for several minutes.`],[t[4],`${name} asks what indoor options are available.`],[t[5],`${name} chooses a movie and popcorn for later in the evening.`]],items:[[`At ${t[0]}, ${name} learned the planned outdoor activity was canceled, raised their voice, and went to the porch.`,'observed','note'],['“That’s not fair. I was ready.”','quote','note'],[`Staff acknowledged ${name}’s disappointment and allowed time before discussing alternatives.`,'staff','note'],[`${name} sat on the porch for several minutes and later asked about indoor options.`,'response','note'],[`${name} chose a movie and popcorn for later in the evening.`,'outcome','note'],['It had rained earlier in the day.','observed','omit'],['There were two chairs on the porch.','observed','omit'],[`${name} threw a fit because plans changed.`,'bad','trash'],[`${name} was refusing to cope.`,'bad','trash'],['Staff got the behavior under control.','bad','trash']]}),
      ()=>({title:'The Broken Mug',setup:`${t[0]} · Kitchen. ${name} drops a favorite mug while putting it away and becomes upset.`,timeline:[[t[0],`${name} drops a ceramic mug on the kitchen floor and the mug breaks.`],[t[1],`${name} says, “That was my favorite,” and begins crying.`],[t[2],`Staff keeps others away from the broken pieces and asks ${name} to stay clear while the area is made safe.`],[t[3],`${name} sits at the table and continues crying.`],[t[4],`${name} asks whether the mug can be replaced.`],[t[5],`After the floor is cleared, ${name} remains at the table and looks online at replacement options with staff.`]],items:[[`At ${t[0]}, ${name} dropped a ceramic mug in the kitchen and the mug broke.`,'observed','note'],['“That was my favorite.”','quote','note'],[`Staff kept others away from the broken pieces and made the area safe while ${name} remained clear of the floor.`,'staff','note'],[`${name} sat at the table, cried, and later asked whether the mug could be replaced.`,'response','note'],[`After the area was cleared, ${name} looked at replacement options with staff.`,'outcome','note'],['The dishwasher was running.','observed','omit'],['There were other mugs in the cabinet.','observed','omit'],[`${name} overreacted to a broken mug.`,'bad','trash'],[`${name} was careless with their belongings.`,'bad','trash'],['Staff calmed the situation down.','bad','trash']]}),
      ()=>({title:'The Knock at the Door',setup:`${t[0]} · Bedroom. ${name} asks for privacy after a housemate repeatedly knocks on their bedroom door.`,timeline:[[t[0],`A housemate knocks on ${name}’s bedroom door for the third time in several minutes.`],[t[1],`${name} opens the door and says loudly, “Stop knocking. I want to be alone.”`],[t[2],`Staff supports separation and reminds the housemate to give ${name} space.`],[t[3],`${name} closes the bedroom door and remains in the room.`],[t[4],`${name} later comes into the hallway and asks whether the housemate is still nearby.`],[t[5],`${name} chooses to make tea in the kitchen after the shared space is quieter.`]],items:[[`At ${t[0]}, a housemate repeatedly knocked on ${name}’s bedroom door; ${name} opened the door and raised their voice.`,'observed','note'],['“Stop knocking. I want to be alone.”','quote','note'],[`Staff supported separation and asked the housemate to give ${name} space.`,'staff','note'],[`${name} closed the bedroom door and remained in the room for several minutes.`,'response','note'],[`${name} later came into the hallway and chose to make tea once the shared space was quieter.`,'outcome','note'],['The bedroom door was already partly closed before the first knock.','observed','omit'],['A lamp was on in the hallway.','observed','omit'],[`${name} was rude to the housemate.`,'bad','trash'],[`${name} was trying to cause conflict.`,'bad','trash'],['Staff appropriately managed both clients.','bad','trash']]})
    ];
    const c=templates[variant]();c.generated=true;return c;
  }

  function trashLesson(text){
    const t=text.toLowerCase();
    if(/dramatic|overreact|rude|careless|obsessing|threw a fit/.test(t))return['LABEL ≠ BEHAVIOR','This is an interpretation of the person, not a concrete description of what happened.','Replace the label with the action, quote, duration, or observable change.'];
    if(/on purpose|trying to|wanted everyone|refusing to cope/.test(t))return['MOTIVE ≠ FACT','This assigns intent that was not directly established.','Document the behavior and the person’s own explanation if they give one.'];
    if(/paranoid/.test(t))return['SYMPTOM LABEL ≠ OBSERVATION','A single statement does not let staff turn a clinical label into the fact of the moment.','Document the exact statement, what was checked, and what was later learned.'];
    if(/successfully|perfectly|appropriately|proved|under control|calmed the situation/.test(t))return['EVALUATION ≠ INTERVENTION','This grades the interaction but hides what staff actually did.','Name the concrete staff action and the person’s response.'];
    if(/disrespectful|out of control|weird|clumsy/.test(t))return['TOO VAGUE','This gives the reader an impression instead of observable behavior.','Use what was seen or heard.'];
    if(/start drama|for attention|trying to upset/.test(t))return['MOTIVE ≠ FACT','Intent is being presented as fact.','Document the observable action and exact words.'];
    if(/handled|everything correctly/.test(t))return['EVALUATION ≠ INTERVENTION','This does not tell the next reader what staff actually did.','Name the actual intervention.'];
    if(/attacked/.test(t))return['LOADED WORD','The wording is broader than the observable action.','Describe the specific physical action.'];
    if(/not paying attention/.test(t))return['CAUSE WITHOUT EVIDENCE','The cause is being guessed.','Document what was observed and anything the person reported.'];
    if(/no big deal/.test(t))return['MINIMIZES THE EVENT','This erases useful assessment and follow-up information.','Document the actual assessment and outcome.'];
    if(/does not respect|knew better|learned their lesson/.test(t))return['MIND-READING','This turns one event into a statement about character or internal knowledge.','Document what the person said or did.'];
    if(/stole/.test(t))return['LEGAL/INTENT LABEL','The word can imply intent that was not established.','Describe that the item was taken and what happened next.'];
    if(/bad seizure|fine after/.test(t))return['VAGUE MEDICAL WORDING','This hides the observable medical details.','Use duration, responsiveness, person report, staff action, and follow-up.'];
    if(/attention-seeking/.test(t))return['MOTIVE ≠ FACT','This labels the purpose of a behavior without evidence.','Document behavior, statement, safety response, and outcome.'];
    if(/was suicidal/.test(t))return['CONCLUSION TOO SOON','One statement does not establish the full level of suicide risk.','Document exact words and the individualized safety assessment/process.'];
    if(/safe because|calmed down/.test(t))return['CALM ≠ SAFE','A quieter appearance alone does not establish safety.','Document assessment, answers, support needs, and handoff.'];
    if(/kept staff awake|nothing important happened/.test(t))return['STAFF-CENTERED OR DISMISSIVE','This centers staff burden or dismisses a meaningful change.','Document the pattern and why it matters for follow-up.'];
    return['NOT A FACT YET','This wording adds judgment, motive, or a conclusion that was not directly established.','Replace it with what you saw, heard, did, or what the person directly reported.'];
  }

  function omitLesson(text){return['TRUE ≠ RELEVANT','This may be accurate, but it does not help explain the event, intervention, response, outcome, or handoff.','Leave it out unless it changes how the reader understands the moment.']}
  function noteLesson(kind){return{observed:['ANCHOR THE EVENT','Specific time, place, and observable action help another reader picture what actually happened.'],quote:['USE THE PERSON’S WORDS','An exact quote can preserve meaning that a label may distort.'],staff:['SHOW THE INTERVENTION','“Supported,” “redirected,” or “de-escalated” are incomplete unless the note says what staff actually did.'],response:['INTERVENTION → RESPONSE','Show what happened after staff acted: accepted, declined, changed, continued, or asked for something else.'],outcome:['CLOSE THE LOOP','Do not end at the peak. Include what changed, continued, or still needed follow-up.']}[kind]}

  function renderCases(){
    const list=$('#caseList');
    list.innerHTML=baseCases.map((c,i)=>`<button class="case-btn ${!generated&&i===current?'active':''}" data-case="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span><b>${c.title}</b></button>`).join('')+`<button class="case-btn generator-btn ${generated?'active':''}" id="caseGenerator"><span class="num">✨</span><b>NEW CASE</b><small>fresh every time</small></button>`;
    list.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>{generated=null;activeLens=null;current=Number(b.dataset.case);resetCase();renderCase()}));
    $('#caseGenerator').addEventListener('click',()=>{generated=buildGeneratedCase();activeLens=pick(lenses);resetCase();renderCase()});
  }

  function renderScene(){const c=caseNow(),moment=c.timeline[sceneIndex],btn=$('#nextMoment');$('#currentMoment').innerHTML=`<div class="moment-time">${moment[0]}</div><div class="moment-text">${moment[1]}</div>`;$('#sceneProgress').textContent=`Moment ${sceneIndex+1} of ${c.timeline.length}`;btn.hidden=false;btn.disabled=false;if(sceneIndex<c.timeline.length-1){btn.textContent='WHAT HAPPENED NEXT? →';btn.classList.remove('done')}else{btn.textContent='START DOCUMENTING →';btn.classList.add('done')}}
  function nextScene(){const c=caseNow();if(sceneIndex<c.timeline.length-1){sceneIndex++;renderScene();return}$('#workspace').hidden=false;$('#nextMoment').hidden=true;renderEvidence();renderSlots();updateCounts();$('#workspace').scrollIntoView({behavior:'smooth',block:'start'})}
  function renderEvidence(){const c=caseNow(),tray=$('#evidenceTray');tray.innerHTML=shuffle(c.items.map((it,i)=>({it,i}))).map(({it,i})=>`<article class="evidence-card" draggable="true" data-card="${i}" tabindex="0"><p>${it[0]}</p><small>Where does this belong?</small><div class="tap-actions"><button type="button" data-action="observed">+ happened</button><button type="button" data-action="quote">+ words</button><button type="button" data-action="staff">+ staff</button><button type="button" data-action="response">+ response</button><button type="button" data-action="outcome">+ follow-through</button><button type="button" data-action="trash">🗑 not documentation</button><button type="button" data-action="omit">📎 leave out</button></div></article>`).join('');tray.querySelectorAll('.evidence-card').forEach(card=>{const id=Number(card.dataset.card);card.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',String(id));card.classList.add('dragging')});card.addEventListener('dragend',()=>card.classList.remove('dragging'));card.addEventListener('click',e=>{if(!e.target.closest('button'))card.classList.toggle('expanded')});card.querySelectorAll('button').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();place(id,b.dataset.action);card.classList.remove('expanded')}))});paintCards()}
  function setupDrops(){document.querySelectorAll('[data-drop]').forEach(zone=>{zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('dragover')});zone.addEventListener('dragleave',()=>zone.classList.remove('dragover'));zone.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('dragover');const id=Number(e.dataTransfer.getData('text/plain'));if(Number.isInteger(id))place(id,zone.dataset.drop)})})}
  function place(id,target){placements[id]=target;$('#draftOutput').hidden=true;const item=caseNow().items[id],expected=item[2];if(target==='trash'){const [tag,why]=trashLesson(item[0]);$('#caseFeedback').innerHTML=expected==='trash'?`<b>🗑️ ${tag}</b><br>${why}`:`<b>🧐 HOLD UP.</b><br>This may be a useful fact. The reviewer will ask whether the note can afford to lose it.`}else if(target==='omit'){const [tag,why]=omitLesson(item[0]);$('#caseFeedback').innerHTML=expected==='omit'?`<b>📎 ${tag}</b><br>${why}`:`<b>🧐 DOES THE NOTE STILL MAKE SENSE?</b><br>You left out a detail that may matter.`}else{const [tag,why]=noteLesson(target);$('#caseFeedback').innerHTML=`<b>✍️ ${tag}</b><br>${why}`}renderSlots();paintCards();updateCounts()}
  function renderSlots(){const c=caseNow();Object.entries(slotIds).forEach(([kind,id])=>{const el=$('#'+id),vals=Object.entries(placements).filter(([,p])=>p===kind).map(([i])=>c.items[Number(i)][0]),wrap=el.closest('.note-slot');if(vals.length){el.innerHTML=vals.map(v=>`<div class="slot-piece">${v}</div>`).join('');wrap.classList.add('filled')}else{el.textContent=prompts[kind];wrap.classList.remove('filled')}})}
  function paintCards(){document.querySelectorAll('.evidence-card').forEach(card=>{card.classList.remove('used','trashed','omitted');const p=placements[Number(card.dataset.card)];if(p&&p!=='trash'&&p!=='omit')card.classList.add('used');if(p==='trash')card.classList.add('trashed');if(p==='omit')card.classList.add('omitted')})}
  function updateCounts(){const vals=Object.values(placements);$('#trashCount').textContent=vals.filter(x=>x==='trash').length;$('#omitCount').textContent=vals.filter(x=>x==='omit').length}
  function makeIssue(it,i,actual){const expected=it[2];if(expected==='note'){if(!actual){const [,why]=noteLesson(it[1]);return{tag:'MISSING PIECE',line:it[0],why,tryInstead:`Add this under ${labels[it[1]]}.`,fix:it[1],i}}if(actual==='trash'||actual==='omit'){const [,why]=noteLesson(it[1]);return{tag:'YOU DROPPED A USEFUL DETAIL',line:it[0],why,tryInstead:`Move it to ${labels[it[1]]}.`,fix:it[1],i}}if(actual!==it[1]){const [,why]=noteLesson(it[1]);return{tag:'RIGHT DETAIL · WRONG HOME',line:it[0],why,tryInstead:`Move this to ${labels[it[1]]}.`,fix:it[1],i}}}if(expected==='trash'&&actual&&actual!=='trash'){const [tag,why,alt]=trashLesson(it[0]);return{tag,line:it[0],why,tryInstead:alt,fix:'trash',i}}if(expected==='omit'&&actual&&actual!=='omit'){const [tag,why,alt]=omitLesson(it[0]);return{tag,line:it[0],why,tryInstead:alt,fix:'omit',i}}return null}
  function priority(issue){if(!activeLens)return 1;const t=(issue.tag+' '+issue.why).toLowerCase(),c=activeLens;if(c.includes('timestamp')&&/time|anchor/.test(t))return 0;if(c.includes('staff')&&/staff|intervention/.test(t))return 0;if(c.includes('judgment')&&/label|motive|judgment|fact/.test(t))return 0;if(c.includes('response')&&/response/.test(t))return 0;if(c.includes('ends')&&/loop|outcome|follow/.test(t))return 0;if(c.includes('irrelevant')&&/relevant/.test(t))return 0;if(c.includes('safety')&&/safe|risk|suicid/.test(t))return 0;return 1}
  function review(){const c=caseNow(),issues=[];c.items.forEach((it,i)=>{const x=makeIssue(it,i,placements[i]);if(x)issues.push(x)});issues.sort((a,b)=>priority(a)-priority(b));const order=['observed','quote','staff','response','outcome'];const text=order.flatMap(kind=>Object.entries(placements).filter(([,p])=>p===kind).map(([i])=>c.items[Number(i)][0])).join(' ');$('#draftText').textContent=text||'No documentation has been built yet.';$('#draftOutput').hidden=false;if(!text)$('#reviewText').innerHTML='<b>🔎 REVIEWER WOULD QUESTION:</b><div class="coach-empty">There is nothing to review yet.</div>';else if(!issues.length)$('#reviewText').innerHTML='<b>✅ REVIEWER CHECK:</b><div class="coach-success"><strong>THIS ONE HOLDS UP.</strong><span>Observable event ✓</span><span>Staff action ✓</span><span>Person response ✓</span><span>Follow-through ✓</span><small>You told the story without making the reader guess.</small></div>';else $('#reviewText').innerHTML='<b>🔎 REVIEWER WOULD QUESTION:</b>'+(generated?`<p class="review-intro">🕵️ This generated case was quietly testing: <strong>${escape(activeLens)}</strong></p>`:'<p class="review-intro">Here is what a reviewer would send back — and why.</p>')+issues.slice(0,6).map(x=>`<article class="coach-card"><span class="coach-tag">${escape(x.tag)}</span><q>${escape(x.line)}</q><div class="coach-why"><strong>WHY?</strong>${escape(x.why)}</div><div class="coach-try"><strong>TRY THIS:</strong>${escape(x.tryInstead)}</div><button type="button" class="coach-fix" data-fix="${x.fix}" data-i="${x.i}">FIX THIS ↗</button></article>`).join('');$('#reviewText').querySelectorAll('.coach-fix').forEach(btn=>btn.addEventListener('click',()=>{place(Number(btn.dataset.i),btn.dataset.fix);review()}));$('#caseFeedback').innerHTML=issues.length?`<b>🔎 CASE COACH:</b><br>${issues.length} thing${issues.length===1?'':'s'} worth another look.`:'<b>✅ CASE COACH:</b><br>Your record tells the story.';$('#draftOutput').scrollIntoView({behavior:'smooth',block:'nearest'})}
  function resetRecord(){placements={};$('#draftOutput').hidden=true;$('#reviewText').innerHTML='';$('#draftText').textContent='';$('#caseFeedback').innerHTML='<b>YOUR TURN.</b><br>Build the record, then send it to review.';renderSlots();updateCounts();renderEvidence()}
  function resetCase(){sceneIndex=0;placements={};$('#workspace').hidden=true;$('#draftOutput').hidden=true;$('#reviewText').innerHTML='';$('#draftText').textContent='';$('#nextMoment').hidden=false;$('#nextMoment').disabled=false}
  function renderCase(){const c=caseNow();$('#caseBadge').textContent=generated?'✨ GENERATED CASE · LENS HIDDEN':`CASE FILE ${String(current+1).padStart(2,'0')}`;$('#caseTitle').textContent=c.title;$('#caseSetup').textContent=c.setup;renderCases();renderScene()}
  function init(){renderCase();setupDrops();$('#nextMoment').addEventListener('click',nextScene);$('#restartScene').addEventListener('click',()=>{resetCase();renderScene()});$('#resetCase').addEventListener('click',resetRecord);$('#reviewCase').addEventListener('click',review)}
  init();
})();