(()=>{
const scenePanel=document.getElementById('scenePanel');
if(!scenePanel)return;
const sceneCount=document.getElementById('sceneCount'),scenePlace=document.getElementById('scenePlace'),sceneTitle=document.getElementById('sceneTitle'),sceneCopy=document.getElementById('sceneCopy'),sceneTask=document.getElementById('sceneTask'),sceneNext=document.getElementById('sceneNext'),stopAudio=document.getElementById('stopAudio'),audioStatus=document.getElementById('audioStatus'),audioTimer=document.getElementById('audioTimer'),voiceMeter=document.getElementById('voiceMeter'),morningTrack=document.getElementById('morningTrack'),afterAudio=document.getElementById('afterAudio'),resetAudio=document.getElementById('resetAudio'),reflectionResult=document.getElementById('reflectionResult'),muteVoices=document.getElementById('muteVoices'),voiceVolume=document.getElementById('voiceVolume'),voiceVolumeValue=document.getElementById('voiceVolumeValue');

const scenes=[
 {place:'BEDROOM · 7:12 AM',title:'You just woke up.',copy:'Your phone buzzed. You need to get dressed and start the day.',task:`<div class="scene-prompt">What do you normally do first?</div><div class="task-choice-row"><button data-pick>get dressed</button><button data-pick>check my phone</button><button data-pick>bathroom first</button></div>`,button:'start the morning →',level:.62},
 {place:'BEDROOM · 7:18 AM',title:'Get dressed.',copy:'One ordinary decision. Pick something and keep moving.',task:`<div class="scene-prompt">What are you throwing on?</div><div class="task-choice-row"><button data-pick>T-shirt</button><button data-pick>hoodie</button><button data-pick>whatever is clean</button></div><div class="task-nudge">No checklist. No right answer. Just make the decision while the voices keep going.</div>`,button:'go to the kitchen →',level:.70},
 {place:'KITCHEN · 7:31 AM',title:'Breakfast. Then remember one thing.',copy:'You are trying to eat, hold onto the next step, and decide what deserves your attention.',task:`<div class="remember-card"><span class="memory-label">HOLD ONTO THIS</span><b>Take your morning medication after breakfast.</b><small>This is part of the exercise, not medical advice.</small></div><div class="scene-prompt">Pick breakfast.</div><div class="task-choice-row"><button data-pick>toast</button><button data-pick>cereal</button><button data-pick>coffee and go</button></div>`,button:'make the grocery list →',level:.82},
 {place:'KITCHEN TABLE · 7:39 AM',title:'Make a grocery list.',copy:'Three ordinary things. Try to keep your place while the voices continue.',task:`<div class="list-card"><input type="text" placeholder="grocery item 1"><input type="text" placeholder="grocery item 2"><input type="text" placeholder="grocery item 3"></div>`,button:'someone is at the door →',level:.72},
 {place:'FRONT ROOM · 7:44 AM',title:'A knock. Then your phone rings.',copy:'Now two real-world interruptions are competing with the voices too.',task:`<div class="door-card"><div><strong>knock knock</strong><p>Someone is at the door.</p></div><span>🚪</span></div><div class="phone-card"><strong>Your phone is ringing.</strong><p>What gets your attention first?</p><div class="task-choice-row"><button data-pick>check the door</button><button data-pick>answer phone</button><button data-pick>freeze for a second</button></div></div>`,button:'get ready to leave →',level:1},
 {place:'BY THE DOOR · 7:51 AM',title:'You are trying to leave.',copy:'Grab what you need. Then see whether that breakfast instruction is still there.',task:`<div class="final-pack task-choice-row"><button data-pick>keys</button><button data-pick>phone</button><button data-pick>wallet / bag</button></div><label>What was the reminder from breakfast?<input id="recallInstruction" type="text" placeholder="type what you remember"></label>`,button:'finish the experience →',level:.88}
];

const humanVoices=new Audio();
humanVoices.loop=true;humanVoices.preload='auto';humanVoices.playsInline=true;
let audioReady=false,current=0,running=false,startTime=0,clockId=null,levelId=null,currentLevel=.62,targetLevel=.62,userVolume=.90,muted=false;

async function ensureAudio(){if(audioReady)return;const r=await fetch('assets/empathy-clear-v3.txt?v=1',{cache:'no-store'});if(!r.ok)throw new Error('audio');const b64=(await r.text()).trim();humanVoices.src='data:audio/mpeg;base64,'+b64;audioReady=true;}
function wirePicks(){sceneTask.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('[data-pick]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')})}
function renderScene(){const s=scenes[current];sceneCount.textContent=`${String(current+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`;scenePlace.textContent=s.place;sceneTitle.textContent=s.title;sceneCopy.textContent=s.copy;sceneTask.innerHTML=s.task;sceneNext.textContent=s.button;[...morningTrack.children].forEach((el,i)=>{el.classList.toggle('active',i===current);el.classList.toggle('done',i<current)});wirePicks();targetLevel=s.level;scenePanel.classList.toggle('surge',s.level>.86);applyVolume();if(running&&!muted)audioStatus.textContent=s.level>.86?'The voices have moved closer. Keep going at your own pace.':'The voices are still there underneath the task.'}
function updateElapsed(){if(!running)return;const sec=Math.floor((Date.now()-startTime)/1000);audioTimer.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function applyVolume(){const level=Math.max(.25,Math.min(1,currentLevel));humanVoices.volume=muted?0:Math.min(1,userVolume*level);voiceMeter.style.width=`${Math.round(level*100)}%`;scenePanel.classList.toggle('voices-muted',muted);muteVoices.classList.toggle('muted',muted);muteVoices.textContent=muted?'🔇 voices muted':'🔊 voices on';}
function startLevelMotion(){if(levelId)clearInterval(levelId);levelId=setInterval(()=>{const wobble=(Math.random()-.5)*.12;currentLevel+=(targetLevel+wobble-currentLevel)*.26;currentLevel=Math.max(.30,Math.min(1,currentLevel));applyVolume();scenePanel.classList.toggle('surge',currentLevel>.86)},700)}
async function startExperience(){if(running)return;try{await ensureAudio();running=true;startTime=Date.now();scenePanel.classList.add('voices-on');stopAudio.disabled=false;humanVoices.currentTime=0;currentLevel=scenes[current].level;applyVolume();await humanVoices.play();audioStatus.textContent=muted?'Voices muted. The morning can continue.':'Recorded voices are on. Use the slider or mute any time.';clockId=setInterval(updateElapsed,1000);startLevelMotion()}catch(e){running=false;stopAudio.disabled=true;audioStatus.textContent='The voice track did not load. Try starting again.'}}
function stopSounds(){if(levelId){clearInterval(levelId);levelId=null}humanVoices.pause();humanVoices.currentTime=0}
function finishExperience(stopped=false){running=false;if(clockId){clearInterval(clockId);clockId=null}stopSounds();scenePanel.classList.remove('voices-on','surge');stopAudio.disabled=true;afterAudio.hidden=false;audioStatus.textContent=stopped?'Stopped. Notice what made you want the sound to end.':'Morning complete. Notice the quiet before you reflect.';afterAudio.scrollIntoView({behavior:'smooth',block:'start'})}

voiceVolume.addEventListener('input',()=>{userVolume=Number(voiceVolume.value)/100;voiceVolumeValue.value=`${voiceVolume.value}%`;if(userVolume>0&&muted)muted=false;if(userVolume===0)muted=true;applyVolume();if(running)audioStatus.textContent=muted?'Voices muted. The morning can continue.':'Voice volume adjusted. The scene will still rise and fall.'});
muteVoices.addEventListener('click',()=>{muted=!muted;applyVolume();audioStatus.textContent=muted?'Voices muted. The morning can continue.':'Voices back on. Use the slider any time.'});
sceneNext.onclick=()=>{if(!running){startExperience();return}if(current<scenes.length-1){current++;renderScene();return}finishExperience(false)};
stopAudio.onclick=()=>finishExperience(true);
resetAudio.onclick=()=>{stopSounds();running=false;current=0;audioTimer.textContent='0:00';afterAudio.hidden=true;scenePanel.classList.remove('voices-on','surge');stopAudio.disabled=true;audioStatus.textContent='Headphones recommended. Set the voice volume where you want it, then start.';currentLevel=.62;renderScene();document.getElementById('audioLab').scrollIntoView({behavior:'smooth',block:'start'})};

document.querySelectorAll('[data-reflect]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-reflect]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const m={focus:'You noticed working memory getting crowded. From the outside that can look like “not listening,” even when someone is working hard to keep up.',irritated:'That irritation matters. Constant competing input can use up patience before anyone else has even asked the next question.',rushed:'Finishing fast can be a coping strategy too. Sometimes “just get it over with” is about escaping overload, not a lack of interest.',voices:'Your attention followed the most intrusive input. That is why “just ignore it” can be such an unrealistic instruction.',fine:'You got through this version easily. A short, voluntary browser exercise is still nothing like living with an involuntary experience that may be more intense, meaningful or persistent.'};reflectionResult.textContent=m[b.dataset.reflect]});
window.addEventListener('pagehide',()=>{if(clockId)clearInterval(clockId);stopSounds()});
voiceVolumeValue.value=`${voiceVolume.value}%`;renderScene();applyVolume();
})();