(()=>{
const scenePanel=document.getElementById('scenePanel');
if(!scenePanel)return;
const sceneCount=document.getElementById('sceneCount'),scenePlace=document.getElementById('scenePlace'),sceneTitle=document.getElementById('sceneTitle'),sceneCopy=document.getElementById('sceneCopy'),sceneTask=document.getElementById('sceneTask'),sceneNext=document.getElementById('sceneNext'),stopAudio=document.getElementById('stopAudio'),audioStatus=document.getElementById('audioStatus'),audioTimer=document.getElementById('audioTimer'),voiceMeter=document.getElementById('voiceMeter'),morningTrack=document.getElementById('morningTrack'),afterAudio=document.getElementById('afterAudio'),resetAudio=document.getElementById('resetAudio'),reflectionResult=document.getElementById('reflectionResult');

const scenes=[
 {place:'BEDROOM · 7:12 AM',title:'You just woke up.',copy:'Your phone buzzed. You need to get dressed and start the day.',task:`<div class="scene-prompt">Before the voices start, pick what you would normally do first.</div><div class="task-choice-row"><button data-pick>get dressed</button><button data-pick>check my phone</button><button data-pick>bathroom first</button></div>`,button:'start the morning →',level:.24},
 {place:'BEDROOM · 7:18 AM',title:'Get dressed.',copy:'Choose something simple. Keep moving even if your attention gets pulled away.',task:`<label>What color shirt would you wear today?<input id="shirtColor" type="text" placeholder="type a color"></label><label class="mini-check"><input type="checkbox"> socks</label><label class="mini-check"><input type="checkbox"> shoes</label>`,button:'go to the kitchen →',level:.42},
 {place:'KITCHEN · 7:31 AM',title:'Breakfast. Then your medication reminder.',copy:'You are trying to eat, remember the next step, and decide what deserves your attention.',task:`<div class="remember-card"><span class="memory-label">REMEMBER THIS FOR LATER</span><b>Take your morning medication after breakfast.</b><small>This is part of the exercise, not medical advice.</small></div><label>What would you eat for breakfast?<input id="breakfastFood" type="text" placeholder="anything ordinary"></label>`,button:'make the grocery list →',level:.66},
 {place:'KITCHEN TABLE · 7:39 AM',title:'Make a grocery list.',copy:'Nothing fancy. Three things you need from the store.',task:`<div class="list-card"><input type="text" placeholder="grocery item 1"><input type="text" placeholder="grocery item 2"><input type="text" placeholder="grocery item 3"></div>`,button:'someone is at the door →',level:.52},
 {place:'FRONT ROOM · 7:44 AM',title:'A knock. Then your phone rings.',copy:'Two ordinary interruptions arrive while the voices are still there.',task:`<div class="door-card"><div><strong>knock knock</strong><p>Someone is at the door.</p></div><span>🚪</span></div><div class="phone-card"><strong>Your phone is ringing.</strong><p>Pick what you would do first.</p><div class="task-choice-row"><button data-pick>check the door</button><button data-pick>answer phone</button><button data-pick>wait a second</button></div></div>`,button:'get ready to leave →',level:.82},
 {place:'BY THE DOOR · 7:51 AM',title:'You are trying to leave.',copy:'Keys. Phone. One last thing: what was the medication reminder?',task:`<div class="final-pack"><label><input type="checkbox">keys</label><label><input type="checkbox">phone</label><label><input type="checkbox">wallet / bag</label></div><label>What was the reminder from breakfast?<input id="recallInstruction" type="text" placeholder="type what you remember"></label>`,button:'finish the experience →',level:.7}
];

const fragments=[
 'they know','you are doing it wrong','why are you here','they are talking about you','everyone can tell','do not look at them','they noticed','do not trust them','they are laughing at you','you forgot something','they can hear you','what are you doing','they are watching','they know what you are thinking','something is wrong','they can see it','keep quiet','they heard that','they are waiting','you messed it up','everyone noticed','what did you forget','they saw that','they are looking','you did it wrong again','they know your name','do not turn around','why are you so slow','you missed something','they are right there','you cannot focus','they heard you','they are talking again','what was next','you forgot again'
];

let current=0,running=false,startTime=0,clockId=null,queueWatcher=null,ctx=null,sources=[],voiceIndex=0,currentLevel=.24,targetLevel=.24,levelId=null;
function renderScene(){
 const s=scenes[current];sceneCount.textContent=`${String(current+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`;scenePlace.textContent=s.place;sceneTitle.textContent=s.title;sceneCopy.textContent=s.copy;sceneTask.innerHTML=s.task;sceneNext.textContent=s.button;[...morningTrack.children].forEach((el,i)=>{el.classList.toggle('active',i===current);el.classList.toggle('done',i<current)});wirePicks();targetLevel=s.level;scenePanel.classList.toggle('surge',s.level>.72);if(running)audioStatus.textContent=s.level>.72?'The voices are closer right now. Keep the volume comfortable.':'The voices are still present. Keep going at your own pace.';
}
function wirePicks(){sceneTask.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('[data-pick]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')})}
function updateElapsed(){if(!running)return;const sec=Math.floor((Date.now()-startTime)/1000);audioTimer.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function browserVoices(){return ('speechSynthesis'in window)?window.speechSynthesis.getVoices():[]}
function pickFragment(){return fragments[Math.floor(Math.random()*fragments.length)]}
function makeStream(){const count=7+Math.floor(Math.random()*6),arr=[];for(let i=0;i<count;i++)arr.push(pickFragment());return arr.join('  ')}
function utter(text,soft){const u=new SpeechSynthesisUtterance(text),vs=browserVoices();if(vs.length){voiceIndex=(voiceIndex+1)%Math.min(vs.length,6);u.voice=vs[voiceIndex]}const vol=Math.max(.08,Math.min(.5,currentLevel*(soft?.34:.62)));u.rate=soft?.78+Math.random()*.15:.95+Math.random()*.18;u.pitch=soft?.58+Math.random()*.2:.72+Math.random()*.3;u.volume=vol;return u}
function fillSpeechQueue(){if(!running||!('speechSynthesis'in window))return;if(!speechSynthesis.speaking&&!speechSynthesis.pending){speechSynthesis.speak(utter(makeStream(),true));speechSynthesis.speak(utter(makeStream(),false));speechSynthesis.speak(utter(makeStream(),true))}}
function startBeds(){try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();const master=ctx.createGain();master.gain.value=.038;master.connect(ctx.destination);const makeBed=(freq,pan,rate,gainVal)=>{const b=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;const src=ctx.createBufferSource();src.buffer=b;src.loop=true;const bp=ctx.createBiquadFilter();bp.type='bandpass';bp.frequency.value=freq;bp.Q.value=.85;const g=ctx.createGain();g.gain.value=gainVal;const lfo=ctx.createOscillator(),lg=ctx.createGain();lfo.frequency.value=rate;lg.gain.value=.12;lfo.connect(lg).connect(g.gain);let tail=g;if(ctx.createStereoPanner){const p=ctx.createStereoPanner();p.pan.value=pan;g.connect(p);tail=p}tail.connect(master);src.connect(bp).connect(g);src.start();lfo.start();sources.push(src,lfo)};makeBed(420,-.72,.6,.52);makeBed(820,.62,1.05,.45);makeBed(1380,-.18,.72,.36)}catch(e){}}
function startLevelMotion(){if(levelId)clearInterval(levelId);levelId=setInterval(()=>{const wobble=(Math.random()-.5)*.2;currentLevel+=(targetLevel+ wobble-currentLevel)*.22;currentLevel=Math.max(.16,Math.min(.9,currentLevel));voiceMeter.style.width=`${Math.round(currentLevel*100)}%`;scenePanel.classList.toggle('surge',currentLevel>.7)},900)}
function stopSounds(){if(queueWatcher){clearInterval(queueWatcher);queueWatcher=null}if(levelId){clearInterval(levelId);levelId=null}if('speechSynthesis'in window)speechSynthesis.cancel();sources.forEach(s=>{try{s.stop()}catch(e){}});sources=[]}
function startExperience(){running=true;startTime=Date.now();scenePanel.classList.add('voices-on');stopAudio.disabled=false;sceneNext.textContent=scenes[current].button;startBeds();fillSpeechQueue();queueWatcher=setInterval(fillSpeechQueue,100);clockId=setInterval(updateElapsed,1000);startLevelMotion();audioStatus.textContent='Voices are on. Some moments will be softer; some will move closer. Stop anytime.'}
function finishExperience(stopped=false){running=false;if(clockId){clearInterval(clockId);clockId=null}stopSounds();scenePanel.classList.remove('voices-on','surge');stopAudio.disabled=true;afterAudio.hidden=false;audioStatus.textContent=stopped?'Stopped. Notice what made you want the sound to end.':'Morning complete. Let the voices stop before you reflect.';afterAudio.scrollIntoView({behavior:'smooth',block:'start'})}
sceneNext.onclick=()=>{if(!running){startExperience();return}if(current<scenes.length-1){current++;renderScene();return}finishExperience(false)};
stopAudio.onclick=()=>finishExperience(true);
resetAudio.onclick=()=>{stopSounds();running=false;current=0;audioTimer.textContent='0:00';afterAudio.hidden=true;scenePanel.classList.remove('voices-on','surge');stopAudio.disabled=true;audioStatus.textContent='Headphones recommended. Audio is off.';currentLevel=.24;voiceMeter.style.width='18%';renderScene();document.getElementById('audioLab').scrollIntoView({behavior:'smooth',block:'start'})};
document.querySelectorAll('[data-reflect]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-reflect]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const m={focus:'You noticed working memory getting crowded. That can look from the outside like “not listening” even when a person is working hard to keep up.',irritated:'That irritation matters. Constant competing input can drain patience before anyone else has even asked the next question.',rushed:'Finishing fast can be a coping strategy too. Sometimes “just get it over with” is about escaping overload, not a lack of interest.',voices:'Your attention followed the most intrusive input. That is exactly why “just ignore it” can be such an unrealistic instruction.',fine:'You got through this version easily. That does not make the lesson disappear: a short, voluntary browser exercise is nothing like living with an involuntary experience that may be more intense, meaningful or persistent.'};reflectionResult.textContent=m[b.dataset.reflect]});
window.addEventListener('pagehide',()=>{if(clockId)clearInterval(clockId);stopSounds()});
renderScene();
})();