(()=>{
const room=document.querySelector('#suicide-room');if(!room)return;
const cases={
quiet:{label:'The quiet comment',desc:'Suicidal thoughts are disclosed, but the person can still participate in safety.',person:'MAYA',steps:[
{stage:'NOTICE',dir:'Maya has been quieter than usual after a hard phone call.',quote:'“I don’t really want to be here anymore.”',side:'Notice the invitation. Do not miss, dismiss, or rush past it.',choices:[
['“You’ve had a rough night. Do you want to talk about it?”',4,'That opens connection, but the suicide meaning is still unclear. Keep going and ask directly.'],
['“When you say you don’t want to be here anymore, are you thinking about suicide?”',-8,'NICE MOVE. You asked directly and calmly instead of making Maya prove how serious the statement was.'],
['“Don’t talk like that. Things will look better tomorrow.”',9,'Reassurance can accidentally shut down the disclosure before you understand what Maya meant.'],
['Stay nearby but avoid asking because you are worried the word suicide could put the idea in Maya’s head.',12,'Avoiding the question leaves the most important information unknown. Asking directly does not create suicidal thoughts.']]
},
{stage:'ASK',dir:'Maya nods and says the thought has been there tonight.',quote:'“Yeah. I’ve thought about suicide. I just want everything to stop.”',side:'Stay calm. Ask one thing at a time. The goal is understanding, not interrogating.',choices:[
['“Thank you for telling me. Help me understand what tonight has been like.”',-7,'You kept the conversation human and gave Maya room to tell the story.'],
['“Do you have a plan? Means? Intent? When? Where?”',8,'The information may matter, but rapid-fire questions can feel like an assessment being done to the person instead of a conversation with them.'],
['“But you don’t really want to die, right?”',11,'This asks Maya to reassure you. Neutral questions make honesty easier.'],
['“You scared me. Why would you say something like that?”',12,'Your fear is understandable, but centering it can add shame and make future disclosure less likely.']]
},
{stage:'UNDERSTAND',dir:'Maya says the thoughts feel intense but also tells you she does not want to act on them and wants help getting through tonight.',quote:'“I don’t want to die. I just don’t want to feel like this.”',side:'Listen for both danger and reasons to choose safety. Ambivalence is information.',choices:[
['Ask what has helped before, who Maya trusts, and what would make the next few hours safer.',-9,'NICE MOVE. You are building safety from what Maya already knows about herself and her supports.'],
['Assume she is safe because she said she does not want to die.',8,'A reason to live matters, but it does not replace understanding current safety and what support is needed now.'],
['Tell her she should be grateful she has people who care.',10,'Gratitude is not a safety intervention and may add shame.'],
['Immediately call 911 without telling Maya what you are doing.',13,'Emergency response may be needed in some situations, but this scenario has not yet shown immediate danger that cannot be managed another way.']]
},
{stage:'SAFETY',dir:'Maya says she can stay safe if she is not alone, can call her sister, and can use her existing safety plan.',quote:'“I think I can get through tonight if I’m not by myself.”',side:'Make safety-for-now concrete: what, when, how, and who.',choices:[
['Work with Maya on the next steps and follow the individualized plan and applicable procedures.',-10,'NICE MOVE. Safety became specific without taking away Maya’s voice.'],
['“Great. Then you’re okay.” Return to normal duties.',10,'A calmer moment does not erase the disclosure. Follow-through matters.'],
['Make every decision for Maya because safety is more important than choice.',7,'Safety can require firm action, but collaboration and dignity still matter whenever the person can participate.'],
['Ask Maya to promise she will not do anything and leave it there.',12,'A promise is not a substitute for a real safety plan or appropriate follow-up.']]
},
{stage:'CONNECT',dir:'The immediate plan is in place. Maya asks what will happen next.',quote:'“Are you going to treat me different now?”',side:'Relationship is part of safety. The person should not learn that honesty costs them connection.',choices:[
['“I’m glad you told me. We’ll keep following the plan, and I’ll tell you what I’m doing as we go.”',-10,'NICE MOVE. You preserved trust while keeping safety follow-through in place.'],
['“That depends on whether you say things like this again.”',13,'That can teach Maya to hide suicidal thoughts next time.'],
['“We already dealt with it. Let’s move on.”',7,'The immediate crisis may be easing, but the relationship and follow-through still matter.'],
['“I’m telling everyone so they know to watch you.”',11,'Share safety information according to role and need, not broadly or as punishment.']]
}]},
more:{label:'More support is needed',desc:'The person says they do not trust themselves alone and wants more help.',person:'ALEX',steps:[
{stage:'NOTICE',dir:'Alex has been pacing after an argument, then goes quiet.',quote:'“I don’t think I can do this anymore.”',side:'Notice the shift and create an opening.',choices:[['“I’m here. When you say you can’t do this anymore, are you thinking about suicide?”',-9,'NICE MOVE. Calm, direct, and connected.'],['“Come on, you’ve gotten through worse.”',8,'This can minimize the current crisis.'],['Say nothing and keep watching.',9,'Observation alone does not answer the safety question.'],['“Don’t say things like that.”',11,'That can shut down disclosure.']]},
{stage:'ASK',dir:'Alex says yes and looks relieved that you asked.',quote:'“Yeah. I’ve been thinking about it a lot tonight.”',side:'Keep the conversation going and understand current safety.',choices:[['“Thank you for telling me. What’s making tonight feel especially hard?”',-8,'You stayed with the story while keeping safety in focus.'],['“Do you have a suicide plan?”',2,'Directness is good, but this can sound clinical if it comes before connection. Keep the conversation natural and one question at a time.'],['“You’re not serious, are you?”',11,'This makes honesty harder.'],['Start explaining hospital rules.',10,'Do not jump ahead before you understand what is happening now.']]},
{stage:'UNDERSTAND',dir:'Alex says they have had thoughts about how they might die and says being alone feels unsafe.',quote:'“I don’t trust myself to be by myself right now.”',side:'This is meaningful safety information. Do not leave the person alone while deciding next steps.',choices:[['“Thank you for telling me. I’m staying with you. We need more support right now, and I want to involve you in what happens next.”',-10,'NICE MOVE. You made the safety shift clear without making help sound like punishment.'],['“Promise me you won’t do anything.”',10,'A promise does not replace safety action.'],['Give space because Alex asked for privacy.',13,'Privacy matters, but Alex just said being alone does not feel safe.'],['Tell Alex they are definitely going to the hospital.',8,'That may or may not become necessary. First use the appropriate crisis/clinical pathway and current safety information.']]},
{stage:'SAFETY',dir:'Alex agrees to get more support and wants you to stay during the call.',quote:'“Can you stay with me while we call someone?”',side:'When safety cannot be managed with ordinary supports, connect to crisis help. 988 can be part of that pathway when appropriate.',choices:[['Stay with Alex and use the appropriate crisis/clinical support, such as 988, while following the setting’s procedures.',-12,'NICE MOVE. You escalated support while preserving connection and involving Alex in the process.'],['Hand Alex the phone and leave.',7,'Connection matters during a vulnerable handoff. Stay involved when possible.'],['Tell Alex that calling 988 is the consequence for saying they are suicidal.',14,'Crisis support should never be framed as punishment for disclosure.'],['Call 911 automatically even though immediate danger is not occurring and Alex is participating in safety.',8,'Emergency services may be needed when danger is immediate or safety cannot be maintained. Use the least invasive appropriate response.']]},
{stage:'CONNECT',dir:'Alex is connected with crisis support and asks whether you are upset.',quote:'“Are you mad that I told you?”',side:'Even if you never see Alex again, this moment can shape whether they tell someone next time.',choices:[['“No. I’m glad you told me. You deserved to be taken seriously and included in what happened next.”',-10,'NICE MOVE. That protects future help-seeking and preserves dignity.'],['“You gave me no choice.”',12,'This adds blame to a safety intervention.'],['“Next time, tell someone sooner.”',6,'Earlier disclosure can help, but this can sound critical after a vulnerable moment.'],['“It’s over now. Don’t think about it.”',8,'The transition may be ending, but the person still deserves closure and connection.']]}
}]},
emergency:{label:'Safety cannot be maintained',desc:'The person reports immediate danger and cannot participate in a safer plan.',person:'DEVON',steps:[
{stage:'NOTICE',dir:'Devon is visibly distressed and says they are afraid of what they might do.',quote:'“I’m scared I’m going to kill myself tonight.”',side:'This is a direct safety statement. Stay present and move into safety-focused support.',choices:[['“I’m really glad you told me. I’m staying with you while we get more help.”',-10,'NICE MOVE. Connection and action can happen at the same time.'],['“You don’t mean that.”',13,'Do not minimize a direct statement of danger.'],['“Calm down first and then we’ll talk.”',10,'Safety cannot wait for calm.'],['Leave to find someone without explaining.',8,'Get help, but maintain connection or ensure another safe support is present.']]},
{stage:'ASK',dir:'Devon says the danger feels immediate.',quote:'“I don’t think I can keep myself safe.”',side:'When immediate safety cannot be maintained, the response changes. Be clear and transparent.',choices:[['“Thank you for telling me. We need emergency help now. I’m going to stay with you and explain what I’m doing.”',-12,'NICE MOVE. Firm safety action does not require abandoning rapport.'],['“If you cooperate, I won’t call anyone.”',15,'Emergency help should not be used as leverage or bargaining.'],['“Promise me you’ll be safe for ten minutes.”',12,'A promise is not enough when immediate safety cannot be maintained.'],['“Why are you doing this to me?”',14,'Keep the focus on Devon’s safety, not staff distress.']]},
{stage:'UNDERSTAND',dir:'Devon cannot identify a safe way to remain in the current setting and the danger is immediate.',quote:'“I need help. I don’t trust myself.”',side:'The goal is no longer to solve everything. The goal is immediate safety and connection to emergency support.',choices:[['Activate emergency response according to the setting’s procedures and keep Devon informed and involved wherever possible.',-14,'NICE MOVE. Emergency action was matched to immediate danger, while dignity and transparency stayed intact.'],['Wait to see if Devon changes their mind.',15,'Immediate danger and inability to maintain safety require action.'],['Send Devon alone to another room while you call.',13,'Do not leave the person alone when immediate safety cannot be maintained.'],['Threaten police involvement to gain compliance.',16,'Emergency support should not be framed as punishment or coercion.']]},
{stage:'SAFETY',dir:'Emergency support is on the way. Devon is frightened about what happens next.',quote:'“Please don’t let them treat me like I’m dangerous.”',side:'Rapport matters during emergency transitions too.',choices:[['“I hear you. I’ll tell you what I know, stay with you when I can, and make sure your concerns are communicated.”',-10,'NICE MOVE. You preserved dignity during a high-acuity handoff.'],['“That’s out of my hands now.”',9,'Your role may change, but relational continuity still matters.'],['“You should have thought of that before.”',15,'Shame can damage trust and future disclosure.'],['Stop talking because the emergency team will handle it.',8,'A handoff does not have to feel like abandonment.']]},
{stage:'CONNECT',dir:'Before the transition, Devon asks one last question.',quote:'“Do you think I did the right thing telling you?”',side:'What the person remembers can affect whether they seek help again.',choices:[['“Yes. Telling me gave us a chance to help keep you alive and get you more support.”',-11,'NICE MOVE. You reinforced disclosure and help-seeking without minimizing the seriousness of the situation.'],['“I guess. Look what happened though.”',11,'This can make emergency help feel like punishment for honesty.'],['“We’ll see.”',8,'The person deserves a clear, supportive answer.'],['“You made this a big deal.”',14,'The danger made it serious; the disclosure made help possible.']]}
}]}}
;
let current='more',step=0;
const q=s=>room.querySelector(s);
function render(){const c=cases[current],m=c.steps[step];q('#srCaseTitle').textContent=c.label;q('#srCaseDesc').textContent=c.desc;q('#srPerson').textContent=c.person;q('#srDirection').textContent=m.dir;q('#srQuote').textContent=m.quote;q('#srSide').textContent=m.side;q('#srChoices').innerHTML='';m.choices.forEach(ch=>{const b=document.createElement('button');b.textContent=ch[0];b.onclick=()=>choose(ch);q('#srChoices').appendChild(b)});q('#srFeedback').hidden=true;q('#srFeedback').classList.remove('warn');q('#srTrack').innerHTML=c.steps.map((x,i)=>`<span class="${i===step?'active':i<step?'done':''}">${i+1}. ${x.stage}</span>`).join('');room.querySelectorAll('.suicide-cases button').forEach(b=>b.classList.toggle('active',b.dataset.case===current));}
function choose(ch){q('#srChoices').innerHTML='';const fb=q('#srFeedback');fb.hidden=false;fb.classList.toggle('warn',ch[1]>4);q('#srFeedbackTitle').textContent=ch[1]<=-7?'✦ NICE MOVE. STAY WITH THE PERSON.':'👀 NOTICE WHAT THIS RESPONSE DOES';q('#srFeedbackText').textContent=ch[2];const btn=q('#srNext');btn.textContent=step<cases[current].steps.length-1?'Keep going →':'Run another path ↻';btn.onclick=()=>{if(step<cases[current].steps.length-1){step++;render()}else{step=0;render();location.hash='#suicide-room'}}}
room.querySelectorAll('.suicide-cases button').forEach(b=>b.onclick=()=>{current=b.dataset.case;step=0;render()});render();
})();