(()=>{
  const room=document.querySelector('#suicide-room'); if(!room)return; const q=s=>room.querySelector(s);
  const cases={
    quiet:{label:'The quiet comment',desc:'Suicidal thoughts are present. Safety may still be supported collaboratively.',person:'MAYA',steps:[
      {stage:'NOTICE',dir:'Maya has been quieter than usual after a hard phone call.',quote:'“I don’t really want to be here anymore.”',side:'Notice the invitation. Do not miss it, dismiss it, or rush past it.',choices:[
        {text:'“You’ve had a rough night. Do you want to talk about it?”',score:2,feedback:'Good opening, but the suicide meaning is still unclear. Keep going and ask directly.',reaction:'Maya looks at the floor. “Maybe. I just don’t want to keep doing this.”',recover:'“When you say you don’t want to keep doing this, are you thinking about suicide?”'},
        {text:'“Maya, sometimes when people say they don’t want to be here anymore, they’re thinking about suicide. Are you thinking about suicide?”',score:-8,feedback:'NICE MOVE. You named the invitation and asked directly. Asking about suicide does not put the idea in someone’s head.',reaction:'Maya is quiet for a few seconds. “Yeah. I have been thinking about suicide.”'},
        {text:'“Don’t say things like that. You’re going to be okay.”',score:10,feedback:'Reassurance can accidentally shut the door right when Maya is trying to tell you something important.',reaction:'Maya goes quiet. “Never mind. I shouldn’t have said anything.”',recover:'“I came in too fast. I do want to hear you. When you said you don’t want to be here, were you talking about suicide?”'},
        {text:'Avoid asking because you are worried saying “suicide” could put the idea in her head.',score:12,feedback:'That worry is common, but asking directly about suicide does not cause or increase suicidal thoughts. Avoiding the question leaves the most important information unknown.',reaction:'Maya notices your hesitation. “You look freaked out. Forget it.”',recover:'“I’m not going anywhere. I want to ask clearly: are you thinking about suicide?”'}]},
      {stage:'ASK',dir:'Maya tells you the thoughts have been present tonight.',quote:'“Yeah. I’ve thought about suicide. I just want everything to stop.”',side:'Stay calm. One question at a time. The goal is understanding, not interrogating.',choices:[
        {text:'“Thank you for telling me. Help me understand what tonight has been like.”',score:-7,feedback:'You kept the conversation human and gave Maya room to tell the story.',reaction:'“Everything piled up. I feel exhausted and trapped.”'},
        {text:'Rapid-fire every risk question you can think of.',score:9,feedback:'The information may matter, but rapid-fire questions can feel like an assessment being done to the person.',reaction:'Maya pulls back. “Can you slow down? I can’t answer all of that.”',recover:'“You’re right. One thing at a time. What feels hardest right now?”'},
        {text:'“But you don’t really want to die, right?”',score:11,feedback:'This asks Maya to reassure you and can make an honest answer harder.',reaction:'Maya shrugs. “I don’t know what you want me to say.”',recover:'“You don’t have to reassure me. I want the real answer. Tell me what the thoughts are like right now.”'},
        {text:'“As long as you don’t say that again, we’re okay.”',score:13,feedback:'This can teach someone that disclosure is the problem.',reaction:'Maya looks at you. “But I HAVE been thinking about suicide. That’s what I’m trying to tell you.”',recover:'“Thank you for correcting me. I’m listening now. Tell me what has been happening.”'}]},
      {stage:'UNDERSTAND',dir:'Maya says the thoughts feel intense but also says she wants help getting through tonight.',quote:'“I don’t want to die. I just don’t want to feel like this.”',side:'Listen for danger and for reasons to choose safety. Both can be true at the same time.',choices:[
        {text:'Ask what has helped before, who Maya trusts, and what would make the next few hours safer.',score:-9,feedback:'NICE MOVE. You are building safety from what Maya already knows about herself and her supports.',reaction:'“My sister helps. And I don’t want to be alone tonight.”'},
        {text:'Assume she is safe because she says she does not want to die.',score:8,feedback:'Wanting to live matters, but it does not replace understanding what support is needed right now.',reaction:'“I still don’t feel safe being by myself.”',recover:'“I hear that. Let’s talk about what would help you stay safe right now.”'},
        {text:'Tell her she should be grateful she has people who care.',score:10,feedback:'Gratitude is not a safety intervention and can add shame.',reaction:'“I know people care. That doesn’t make this stop.”',recover:'“You’re right. I want to understand what would help tonight.”'},
        {text:'Immediately call emergency services without telling Maya what you are doing.',score:12,feedback:'Emergency response may be needed, but hiding what you are doing can damage trust when immediate danger has not been established.',reaction:'“Wait—what are you doing?”',recover:'“I should have told you before acting. I want to keep you involved. Let’s figure out the safest next step together.”'}]},
      {stage:'SAFETY',dir:'Maya says she can participate in staying safe if she is not alone and can use her existing supports.',quote:'“I think I can get through tonight if I’m not by myself.”',side:'Make safety-for-now concrete: what, when, how and who.',choices:[
        {text:'Work with Maya on next steps using her individualized plan and the procedures for the setting.',score:-10,feedback:'NICE MOVE. Safety became specific without taking away Maya’s voice.',reaction:'“Okay. Can we call my sister together?”'},
        {text:'“Great. Then you’re okay.” Return to normal duties.',score:10,feedback:'A calmer moment does not erase the disclosure. Follow-through matters.',reaction:'“Wait… I said I don’t want to be alone.”',recover:'“You’re right. I moved too fast. I’m staying while we put the plan in place.”'},
        {text:'Make every decision for Maya because safety is more important than choice.',score:7,feedback:'Safety can require firm action, but collaboration still matters whenever the person can participate.',reaction:'“Can I at least know what’s happening?”',recover:'“Yes. I want you involved. Let’s go through the next steps together.”'},
        {text:'Ask Maya to promise she will not do anything and leave it there.',score:12,feedback:'A promise is not a substitute for a real plan or appropriate follow-through.',reaction:'“I can promise, but I still don’t want to be alone.”',recover:'“That tells me we still need a real plan for tonight.”'}]},
      {stage:'CONNECT',dir:'The immediate plan is in place. Maya asks what this changes between you.',quote:'“Are you going to treat me different now?”',side:'Relationship is part of safety. Honesty should not cost the person connection.',choices:[
        {text:'“I’m glad you told me. I’ll keep you informed about what happens next.”',score:-10,feedback:'NICE MOVE. You preserved trust while keeping safety follow-through in place.',reaction:'“Okay. I was scared to tell anyone.”'},
        {text:'“That depends on whether you say things like this again.”',score:13,feedback:'That can teach Maya to hide suicidal thoughts next time.',reaction:'“Then maybe I shouldn’t tell people.”',recover:'“No. I want you to tell someone when this happens. I’m sorry I made honesty sound like a problem.”'},
        {text:'“We already dealt with it. Let’s move on.”',score:7,feedback:'The immediate danger may be easing, but the relationship still matters.',reaction:'“I just wanted to know if you’re mad.”',recover:'“I’m not mad. I’m glad you told me.”'},
        {text:'“I’m telling everyone so they know to watch you.”',score:11,feedback:'Share safety information according to role and need, not broadly or as punishment.',reaction:'“Everyone?”',recover:'“I said that badly. I’ll only share what needs to be shared for support and safety.”'}]}
    ]},
    more:{label:'More support is needed',desc:'The conversation reveals that Alex does not feel safe being alone and wants more support.',person:'ALEX',steps:[
      {stage:'NOTICE',dir:'Alex has been pacing since an argument. They finally sit down, rub their face and stare at the floor.',quote:'“I’m so tired. I can’t keep doing this.”',side:'You do not know what “this” means yet. Treat the words as an invitation to get curious.',choices:[
        {text:'“You sound exhausted. What feels like too much right now?”',score:-7,feedback:'NICE MOVE. You explored Alex’s words before deciding what they meant.',reaction:'“Everything. The fighting. Feeling like I keep screwing everything up. I’m tired of waking up to the same thing.”'},
        {text:'“What do you mean you can’t do this anymore?”',score:-6,feedback:'Good. An open question gives Alex room to tell you what “this” means.',reaction:'“All of it. I’m exhausted. I don’t want another day like this.”'},
        {text:'“Come on, you’ve gotten through worse.”',score:8,feedback:'This tries to reassure Alex before you know what they are trying to tell you.',reaction:'“That doesn’t mean I want to keep doing it.”',recover:'“You’re right. I jumped to reassurance. What do you mean when you say you don’t want to keep doing it?”'},
        {text:'Say nothing and keep watching.',score:9,feedback:'You noticed the change, but Alex has given you an opening. Observation alone will not tell you what the words mean.',reaction:'“Are you going to say something?”',recover:'“Yeah. You said you can’t keep doing this. What feels like too much right now?”'}]},
      {stage:'ASK',dir:'Alex has said they are exhausted, do not want another day like this, and are tired of waking up to the same pain.',quote:'“I just want it all to stop.”',side:'Now there are several invitations. Name what you heard and ask directly. Asking does not put suicide into someone’s head.',choices:[
        {text:'“Alex, you’ve said you’re exhausted, you don’t want another day like this, and you want it all to stop. Sometimes when people feel that way, they’re thinking about suicide. Are you thinking about dying by suicide?”',score:-10,feedback:'NICE MOVE. You connected the question to Alex’s own words and asked directly instead of making Alex hint harder.',reaction:'Alex is quiet, then nods. “Yeah. I’ve been thinking about suicide.”'},
        {text:'“You’re not going to do anything stupid, are you?”',score:12,feedback:'This adds judgment and pressures Alex to reassure you.',reaction:'“Forget it.”',recover:'“That came out wrong. I’m concerned because of what you’ve been saying. Are you thinking about suicide?”'},
        {text:'Keep asking general questions because saying the word suicide might put the idea in Alex’s head.',score:13,feedback:'That fear is common, but asking directly about suicide does not cause or increase suicidal thoughts.',reaction:'“I feel like I’m trying to tell you without actually saying it.”',recover:'“I hear that. I’m going to ask directly: are you thinking about suicide?”'},
        {text:'“You just need some sleep. Let’s talk tomorrow.”',score:11,feedback:'Exhaustion does not explain away the invitations Alex has given you.',reaction:'“I don’t know if I want there to be a tomorrow.”',recover:'“Thank you for saying that. Are you thinking about suicide?”'}]},
      {stage:'UNDERSTAND',dir:'Alex says yes. The direct question did not end the conversation; it opened it.',quote:'“Yeah. I’ve been thinking about suicide. I don’t want to scare anybody, but I don’t trust myself alone tonight.”',side:'The level of concern has changed. Keep listening, stay with Alex and move toward more support.',choices:[
        {text:'“Thank you for telling me. I’m staying with you. We need more support tonight, and I want to keep you involved in what happens next.”',score:-10,feedback:'NICE MOVE. You took the disclosure seriously without making Alex regret telling you.',reaction:'“Okay. I don’t want to be alone with this.”'},
        {text:'“Promise me you won’t do anything.”',score:10,feedback:'A promise does not answer the safety need Alex just identified.',reaction:'“I can promise, but I literally just told you I don’t trust myself alone.”',recover:'“You’re right. A promise isn’t enough here. I’m staying with you while we get more support.”'},
        {text:'Give Alex privacy so they can calm down.',score:13,feedback:'Normally space can help. Here, Alex has specifically told you they do not feel safe alone.',reaction:'“Wait. Please don’t leave me.”',recover:'“I’m staying. We can give you as much privacy as we safely can without leaving you alone.”'},
        {text:'“Okay, then you’re definitely going to the hospital.”',score:8,feedback:'Do not make help sound like an automatic consequence of disclosure.',reaction:'“Is that the only thing that happens when I tell the truth?”',recover:'“No. I moved too far ahead. We need more support right now, and I want you involved in the safest next step.”'}]},
      {stage:'SAFETY',dir:'Alex is willing to accept more help and asks you not to leave during the handoff.',quote:'“Can you stay with me while we call someone?”',side:'When ordinary supports are not enough, connect to more help. 988 can be part of that pathway when appropriate.',choices:[
        {text:'Stay with Alex and connect with appropriate crisis or clinical support, such as 988, while following the setting’s procedures.',score:-12,feedback:'NICE MOVE. You increased support while preserving connection and involving Alex.',reaction:'“Okay. Let’s call.”'},
        {text:'Hand Alex the phone and leave.',score:7,feedback:'Connection matters during a vulnerable handoff.',reaction:'“Wait. I asked if you could stay.”',recover:'“Yes. I’m staying with you while we make the call.”'},
        {text:'Tell Alex that calling 988 is the consequence for saying they are suicidal.',score:14,feedback:'Crisis support should never be framed as punishment for disclosure.',reaction:'“So I get punished for telling the truth?”',recover:'“No. I said that wrong. This is about adding support, not punishing you.”'},
        {text:'Call emergency services automatically even though Alex is participating in safety and immediate danger is not occurring.',score:8,feedback:'Emergency response may be needed when danger is immediate or safety cannot be maintained. Match the response to the situation.',reaction:'“I’m talking to you and asking for help. Why are you skipping straight there?”',recover:'“You’re right to ask. Let’s use the appropriate crisis support and keep reassessing safety.”'}]},
      {stage:'CONNECT',dir:'Alex is connected with more support and asks whether you are upset.',quote:'“Are you mad that I told you?”',side:'Even if you never see Alex again, this moment can shape whether they tell someone next time.',choices:[
        {text:'“No. I’m glad you told me. You deserved to be taken seriously and included.”',score:-10,feedback:'NICE MOVE. That protects future help-seeking and preserves dignity.',reaction:'“Okay. I was afraid everyone would freak out.”'},
        {text:'“You gave me no choice.”',score:12,feedback:'This adds blame to a safety intervention.',reaction:'“That makes me wish I hadn’t told you.”',recover:'“I’m sorry. Telling me was the right thing. My job is to respond safely without blaming you.”'},
        {text:'“Next time, tell someone sooner.”',score:6,feedback:'Earlier disclosure can help, but this can sound critical after a vulnerable moment.',reaction:'“I did tell someone. I told you.”',recover:'“You’re right. And I’m glad you did.”'},
        {text:'“It’s over now. Don’t think about it.”',score:8,feedback:'The transition may be ending, but the person still deserves closure and connection.',reaction:'“It doesn’t feel over to me.”',recover:'“That makes sense. I’m still here while the next support takes over.”'}]}
    ]},
    emergency:{label:'Safety cannot be maintained',desc:'The person reports immediate danger and cannot participate in a safer plan.',person:'DEVON',steps:[
      {stage:'NOTICE',dir:'Devon is visibly distressed and says they are afraid of what they might do.',quote:'“I’m scared I’m going to kill myself tonight.”',side:'This is a direct safety statement. Stay present and move into safety-focused support.',choices:[
        {text:'“I’m really glad you told me. I’m staying with you while we get more help.”',score:-10,feedback:'NICE MOVE. Connection and action can happen at the same time.',reaction:'“Please don’t leave me.”'},
        {text:'“You don’t mean that.”',score:13,feedback:'Do not minimize a direct statement of danger.',reaction:'“I do mean it. That’s why I told you.”',recover:'“I believe you. I’m staying with you and getting help now.”'},
        {text:'“Calm down first and then we’ll talk.”',score:10,feedback:'Safety cannot wait for calm.',reaction:'“I’m telling you because I’m not calm and I’m scared.”',recover:'“You’re right. We can act on safety while you’re scared.”'},
        {text:'Leave to find someone without explaining.',score:8,feedback:'Get help, but maintain connection or make sure another support person stays present whenever possible.',reaction:'“Wait—where are you going?”',recover:'“I’m getting more help, and I’m making sure you’re not alone while we do that.”'}]},
      {stage:'ASK',dir:'Devon says the danger feels immediate.',quote:'“I don’t think I can keep myself safe.”',side:'You need enough information to recognize that immediate safety cannot be maintained; you do not need to turn this into an interrogation.',choices:[
        {text:'“Thank you for telling me. I’m staying with you. We’re getting emergency help now, and I’ll tell you what’s happening.”',score:-12,feedback:'NICE MOVE. You were clear about the safety action and kept Devon in the relationship.',reaction:'“Okay. Just don’t leave me alone.”'},
        {text:'Keep asking questions until Devon calms down.',score:12,feedback:'The goal is not to question someone into calm when they are reporting immediate danger.',reaction:'“I already told you I don’t feel safe.”',recover:'“You’re right. I have enough to know we need emergency help now. I’m staying with you.”'},
        {text:'Tell Devon to promise they will wait while you finish another task.',score:14,feedback:'Immediate danger cannot be managed by a promise or delayed for routine tasks.',reaction:'“I don’t know if I can promise that.”',recover:'“Then I’m staying here and getting emergency help now.”'},
        {text:'Argue that Devon has too much to live for.',score:9,feedback:'Reasons for living can matter, but arguing does not replace immediate safety action.',reaction:'“I know people care. I’m still scared of what I might do.”',recover:'“I hear you. We’re acting on safety now.”'}]},
      {stage:'UNDERSTAND',dir:'Devon remains unable to participate in a safer plan.',quote:'“I need somebody to help me stay alive right now.”',side:'Safety action has to lead. Keep communication calm and transparent.',choices:[
        {text:'Activate the appropriate emergency response for the setting and keep Devon informed and accompanied as much as possible.',score:-12,feedback:'NICE MOVE. Emergency action does not require abandoning connection.',reaction:'“Okay. Tell me what’s happening.”'},
        {text:'Wait to see if Devon changes their mind.',score:14,feedback:'Immediate danger and inability to maintain safety require action now.',reaction:'“Please help me.”',recover:'“I am. I’m activating emergency support now and staying with you.”'},
        {text:'Threaten emergency services if Devon does not calm down.',score:14,feedback:'Emergency response is a safety action, not a threat or punishment.',reaction:'“So I’m in trouble?”',recover:'“No. You’re not in trouble. We’re getting help because you told me you’re in danger.”'},
        {text:'Tell Devon there is nothing else you can do.',score:14,feedback:'There is a next step: activate the appropriate emergency response and maintain connection.',reaction:'“Then why did I tell you?”',recover:'“Telling me mattered. It lets us act to keep you safe.”'}]},
      {stage:'SAFETY',dir:'Emergency support is being activated.',quote:'“What’s going to happen to me?”',side:'Be honest about what you know, avoid promises you cannot make, and keep the person involved where possible.',choices:[
        {text:'Explain the next step you know, acknowledge what you do not know, and stay connected through the handoff.',score:-10,feedback:'NICE MOVE. Transparency can reduce the sense that safety is being done to the person.',reaction:'“Okay. Just keep telling me what’s happening.”'},
        {text:'“I don’t know. It’s out of my hands now.”',score:9,feedback:'You may not control the outcome, but you can still communicate and support the transition.',reaction:'“That makes this scarier.”',recover:'“I don’t know every next step, but I’ll tell you what I do know and stay with you through the handoff.”'},
        {text:'Promise Devon they definitely will not go to the hospital.',score:12,feedback:'Do not promise an outcome you cannot control.',reaction:'“Are you sure?”',recover:'“I shouldn’t promise that. I can promise to keep you informed about what I know.”'},
        {text:'Stop talking because the emergency team will handle it.',score:8,feedback:'A handoff does not have to feel like abandonment.',reaction:'“Can you at least tell me what’s happening?”',recover:'“Yes. I’ll keep you informed while we transition.”'}]},
      {stage:'CONNECT',dir:'Before the transition, Devon asks one last question.',quote:'“Do you think I did the right thing telling you?”',side:'What the person remembers can affect whether they seek help again.',choices:[
        {text:'“Yes. Telling me gave us a chance to get you more support and keep you safe.”',score:-11,feedback:'NICE MOVE. You reinforced disclosure and help-seeking.',reaction:'“Okay. I’m glad I said something.”'},
        {text:'“I guess. Look what happened though.”',score:11,feedback:'This can make emergency help feel like punishment for honesty.',reaction:'“That makes me wish I kept it to myself.”',recover:'“I don’t want that to be the lesson. Telling me was the right move.”'},
        {text:'“We’ll see.”',score:8,feedback:'The person deserves a clear, supportive answer.',reaction:'“That doesn’t make me feel like I should tell someone next time.”',recover:'“Then let me be clear: yes, you did the right thing telling me.”'},
        {text:'“You made this a big deal.”',score:14,feedback:'The danger made it serious; the disclosure made help possible.',reaction:'Devon looks ashamed. “Sorry.”',recover:'“You do not need to apologize for asking for help.”'}]}
    ]}
  };
  let current='quiet',step=0;
  function updateTrack(){const c=cases[current];q('#srTrack').innerHTML=c.steps.map((x,i)=>`<span class="${i===step?'active':i<step?'done':''}">${i+1}. ${x.stage}</span>`).join('')}
  function render(){const c=cases[current],m=c.steps[step];q('#srCaseTitle').textContent=c.label;q('#srCaseDesc').textContent=c.desc;q('#srPerson').textContent=c.person;q('#srDirection').textContent=m.dir;q('#srQuote').textContent=m.quote;q('#srSide').textContent=m.side;q('#srFeedback').hidden=true;q('#srFeedback').classList.remove('warn');q('#srChoices').innerHTML='';m.choices.forEach(ch=>{const b=document.createElement('button');b.type='button';b.textContent=ch.text;b.onclick=()=>choose(ch);q('#srChoices').appendChild(b)});updateTrack();room.querySelectorAll('.suicide-cases button').forEach(b=>b.classList.toggle('active',b.dataset.case===current))}
  function choose(ch){const fb=q('#srFeedback');fb.hidden=false;fb.classList.toggle('warn',ch.score>4);q('#srFeedbackTitle').textContent=ch.score<=-7?'✦ NICE MOVE. STAY WITH THE PERSON.':'👀 THE CONVERSATION CHANGED';q('#srFeedbackText').innerHTML=`${ch.feedback}<br><br><strong>${cases[current].person}:</strong> ${ch.reaction}`;q('#srDirection').textContent=ch.score>4?'Your response landed. The conversation is not over. You can recover from here.':'The conversation keeps moving.';q('#srQuote').textContent=ch.reaction;q('#srChoices').innerHTML='';const next=q('#srNext');if(ch.score>4&&ch.recover){next.textContent='Repair and keep going →';next.onclick=()=>renderRecovery(ch)}else{next.textContent=step<cases[current].steps.length-1?'Keep going →':'Choose another path ↻';next.onclick=advance}}
  function renderRecovery(ch){q('#srFeedback').hidden=true;q('#srDirection').textContent='You get another opening. Try repairing the moment instead of restarting the scenario.';q('#srQuote').textContent=ch.reaction;q('#srSide').textContent='A clumsy response does not end the relationship. Own it, clarify, and keep the person talking.';q('#srChoices').innerHTML='';const good=document.createElement('button');good.type='button';good.textContent=ch.recover;good.onclick=()=>{q('#srFeedback').hidden=false;q('#srFeedback').classList.remove('warn');q('#srFeedbackTitle').textContent='✦ NICE RECOVERY. YOU STAYED IN IT.';q('#srFeedbackText').textContent='You corrected your approach without making the person start over. Repair is a real skill.';const next=q('#srNext');next.textContent=step<cases[current].steps.length-1?'Keep going →':'Choose another path ↻';next.onclick=advance};const avoid=document.createElement('button');avoid.type='button';avoid.textContent='Avoid the topic and move on.';avoid.onclick=()=>{q('#srFeedback').hidden=false;q('#srFeedback').classList.add('warn');q('#srFeedbackTitle').textContent='👀 NOTICE THE LOST OPENING';q('#srFeedbackText').textContent='Avoiding the topic may make future disclosure less likely. The scenario still continues, but now you are carrying a rupture into the next moment.';const next=q('#srNext');next.textContent=step<cases[current].steps.length-1?'Keep going anyway →':'Choose another path ↻';next.onclick=advance};q('#srChoices').append(good,avoid)}
  function advance(){if(step<cases[current].steps.length-1){step++;render()}else{step=0;render();window.scrollTo({top:room.offsetTop,behavior:'smooth'})}}
  room.querySelectorAll('.suicide-cases button').forEach(b=>b.addEventListener('click',()=>{current=b.dataset.case;step=0;render()}));render();
})();